export {default as Navbar} from "./Navbar"
export {default as Home} from "./Home"
export {default as Cryptocurrencies} from "./Cryptocurrencies"
export {default as News} from "./News"
export {default as Cryptodetails} from "./Cryptodetails"
export {default as Linegraph} from "./Linegraph"